name: Update issues that have been responded to.

on:
  issue_comment:
    types: [created]

jobs:
  remove-label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if(context.payload.sender.login === 'neverendingqs') {
              github.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'awaiting response',
              })
            }

