name: Update issues that have been responded to.

on:
  issue_comment:
    types: [created]

jobs:
  remove-label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context.payload.sender.login);
