name: Update issues that have been responded to.

on:
  issue_comment:
    types: [created]

jobs:
  remove-label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const label = 'awaiting response';
            const isContributor = context.payload.sender.login === 'neverendingqs';
            const hasLabel = context.payload.issue.labels
              .map(({ name }) => name)
              .includes(label);
            
            console.log(JSON.stringify({
              labels: context.payload.issue.labels,
              login: context.payload.sender.login
            }));
            
            if(isContributor && hasLabel) {
              github.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: label,
              });
            }

